### ISSUE TITLE
InvalidURI error

### ISSUE THREAD

**Issue by AlanReviews** [usnistgov/MDCS#10]
I called celery -A mdcs worker -l info -Ofair --purge and I received an invalidURI error. Here is the log:
```txt
Traceback (most recent call last):
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\kombu\utils\objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alan\Envs\mdcs_env\Scripts\celery.exe\__main__.py", line 7, in <module>
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\__main__.py", line 16, in main
    _main()
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\celery.py", line 476, in handle_argv
    return self.execute(command, argv)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\celery.py", line 408, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\worker.py", line 221, in run_from_argv
    *self.parse_options(prog_name, argv, command))
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\base.py", line 397, in parse_options
    self.parser = self.create_parser(prog_name, command)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\base.py", line 413, in create_parser
    self.add_arguments(parser)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\bin\worker.py", line 277, in add_arguments
    default=conf.worker_state_db,
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\utils\collections.py", line 129, in __getattr__
    return self[k]
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\utils\collections.py", line 432, in __getitem__
    return getitem(k)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\utils\collections.py", line 281, in __getitem__
    return mapping[_key]
  File "c:\program files\python36\lib\collections\__init__.py", line 987, in __getitem__
    if key in self.data:
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\kombu\utils\objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\app\base.py", line 139, in data
    return self.callback()
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\app\base.py", line 902, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\app\base.py", line 912, in _load_config
    self.loader.config_from_object(self._config_source)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\loaders\base.py", line 131, in config_from_object
    self._conf = force_mapping(obj)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\celery\utils\collections.py", line 49, in force_mapping
    if isinstance(m, (LazyObject, LazySettings)):
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\django\utils\functional.py", line 256, in inner
    self._setup()
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "c:\program files\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\mdcs\mdcs-master\mdcs\settings.py", line 296, in <module>
    connect(DB_NAME, host=MONGODB_URI)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\mongoengine\connection.py", line 376, in connect
    register_connection(alias, db, **kwargs)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\mongoengine\connection.py", line 193, in register_connection
    **kwargs)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\mongoengine\connection.py", line 105, in _get_connection_settings
    uri_dict = uri_parser.parse_uri(entity)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\pymongo\uri_parser.py", line 319, in parse_uri
    user, passwd = parse_userinfo(userinfo)
  File "c:\users\alan\envs\mdcs_env\lib\site-packages\pymongo\uri_parser.py", line 89, in parse_userinfo
    "RFC 3986, use %s()." % quote_fn)
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus().
```

**Comment by Guillaume-sousa** [comment]
You may be using special characters in your settings.py for `MONGO_USER` and `MONGO_PASSWORD` values.

You will probably need to escape those characters when building the `MONGODB_URI`. See an example here: https://stackoverflow.com/a/39283299

**Comment by Guillaume-sousa** [comment]
This seems to be an issue with the settings and should be solved by using `urllib.parse.quote_plus()` as suggested in the error message. I am closing this one for now. Let us know if you any other issues.
